/* This file contains stub implementations of the AUTOSAR RTE functions.
   The stub implementations can be used for testing the generated code in
   Simulink, for example, in SIL/PIL simulations of the component under
   test. Note that this file should be replaced with an appropriate RTE
   file when deploying the generated code outside of Simulink.

   This file is generated for:
   Atomic software component:  "ADLK"
   ARXML schema: "4.3"
   File generated on: "25-Oct-2023 11:40:52"  */

#ifndef Rte_ADLK_h
#define Rte_ADLK_h
#include "Rte_Type.h"
#include "Compiler.h"

/* Data access functions */
#define Rte_Write_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg Rte_Write_ADLK_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg(void);

#define Rte_Write_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg Rte_Write_ADLK_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg(void);

#define Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (void);

#define Rte_Read_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg Rte_Read_ADLK_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg Rte_Read_ADLK_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg Rte_Read_ADLK_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg Rte_Read_ADLK_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg
  (Boolean* u);

#define Rte_Read_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg
  (Boolean* u);

#define Rte_Read_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg Rte_Read_ADLK_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg

Std_ReturnType Rte_Read_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg
  (Boolean* u);

#define Rte_Read_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg Rte_Read_ADLK_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg

Std_ReturnType Rte_Read_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg
  (Boolean* u);

#define Rte_Write_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FLUnlock_flg_VbOUT_ADLK_FLUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg Rte_Write_ADLK_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg(Boolean
  u);

#define Rte_Invalidate_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RLUnlock_flg_VbOUT_ADLK_RLUnlock_flg
  (void);

#define Rte_Write_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg Rte_Write_ADLK_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_FLLock_flg_VbOUT_ADLK_FLLock_flg(void);

#define Rte_Write_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg Rte_Write_ADLK_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg(Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg

Std_ReturnType Rte_Invalidate_VbOUT_ADLK_RLLock_flg_VbOUT_ADLK_RLLock_flg(void);

#define Rte_Write_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg Rte_Write_ADLK_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_FLDoorMotorA_flg_VbOUT_ADLK_FLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg Rte_Write_ADLK_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg Rte_Invalidate_ADLK_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_FLDoorMotorB_flg_VbOUT_ADLK_FLDoorMotorB_flg(void);

#define Rte_Write_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg Rte_Write_ADLK_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_RLDoorMotorA_flg_VbOUT_ADLK_RLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg Rte_Write_ADLK_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg Rte_Invalidate_ADLK_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_ADLK_RLDoorMotorB_flg_VbOUT_ADLK_RLDoorMotorB_flg(void);

#define Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (void);

/* Entry point functions */
extern FUNC(void, ADLK_CODE) ADLK_Init(void);
extern FUNC(void, ADLK_CODE) ADLK_Step(void);

#endif
