/* This file contains stub implementations of the AUTOSAR RTE functions.
   The stub implementations can be used for testing the generated code in
   Simulink, for example, in SIL/PIL simulations of the component under
   test. Note that this file should be replaced with an appropriate RTE
   file when deploying the generated code outside of Simulink.

   This file is generated for:
   Atomic software component:  "ADLK"
   ARXML schema: "4.3"
   File generated on: "06-Dec-2023 17:54:38"  */

#ifndef Rte_ADLK_h
#define Rte_ADLK_h
#include "Rte_Type.h"
#include "Compiler.h"

/* Data access functions */
#define Rte_Write_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig Rte_Write_ADLK_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig

Std_ReturnType Rte_Write_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig(UInt8
  u);

#define Rte_Invalidate_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig

Std_ReturnType Rte_Invalidate_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig Rte_Write_ADLK_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig

Std_ReturnType Rte_Write_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig(UInt8
  u);

#define Rte_Invalidate_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig

Std_ReturnType Rte_Invalidate_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig Rte_Write_ADLK_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig Rte_Write_ADLK_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct Rte_Write_ADLK_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct Rte_Invalidate_ADLK_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct
  (void);

#define Rte_Write_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct Rte_Write_ADLK_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct Rte_Invalidate_ADLK_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct
  (void);

#define Rte_Read_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg Rte_Read_ADLK_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FLLock_flg_VbOUT_DLK_FLLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg Rte_Read_ADLK_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_FLUnlock_flg_VbOUT_DLK_FLUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg Rte_Read_ADLK_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RLLock_flg_VbOUT_DLK_RLLock_flg(Boolean* u);

#define Rte_Read_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg Rte_Read_ADLK_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg

Std_ReturnType Rte_Read_VbOUT_DLK_RLUnlock_flg_VbOUT_DLK_RLUnlock_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_FLDoorFullOpen_flg_VbOUT_HWA_FLDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg Rte_Read_ADLK_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg

Std_ReturnType
  Rte_Read_VbOUT_HWA_RLDoorFullOpen_flg_VbOUT_HWA_RLDoorFullOpen_flg(Boolean* u);

#define Rte_Read_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg
  (Boolean* u);

#define Rte_Read_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Read_ADLK_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType Rte_Read_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg
  (Boolean* u);

#define Rte_Read_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg Rte_Read_ADLK_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg

Std_ReturnType Rte_Read_VbOUT_SP_FLDoorAjarSts_flg_VbOUT_SP_FLDoorAjarSts_flg
  (Boolean* u);

#define Rte_Read_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg Rte_Read_ADLK_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg

Std_ReturnType Rte_Read_VbOUT_SP_RLDoorAjarSts_flg_VbOUT_SP_RLDoorAjarSts_flg
  (Boolean* u);

#define Rte_Write_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig Rte_Write_ADLK_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig

Std_ReturnType Rte_Write_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig(UInt8
  u);

#define Rte_Invalidate_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig

Std_ReturnType Rte_Invalidate_VeOUT_ADLK_FLLockReq_sig_VeOUT_ADLK_FLLockReq_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig Rte_Write_ADLK_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig

Std_ReturnType Rte_Write_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig(UInt8
  u);

#define Rte_Invalidate_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig

Std_ReturnType Rte_Invalidate_VeOUT_ADLK_RLLockReq_sig_VeOUT_ADLK_RLLockReq_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLReleaseLatchStatus_sig_VeOUT_ADLK_FLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Write_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLReleaseLatchStatus_sig_VeOUT_ADLK_RLReleaseLatchStatus_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig Rte_Write_ADLK_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig Rte_Invalidate_ADLK_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLDoorMotorCmd_sig_VeOUT_ADLK_FLDoorMotorCmd_sig
  (void);

#define Rte_Write_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig Rte_Write_ADLK_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig Rte_Invalidate_ADLK_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLDoorMotorCmd_sig_VeOUT_ADLK_RLDoorMotorCmd_sig
  (void);

#define Rte_Write_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct Rte_Write_ADLK_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct

Std_ReturnType
  Rte_Write_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct Rte_Invalidate_ADLK_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_FLDoorMotorPWM_pct_VeOUT_ADLK_FLDoorMotorPWM_pct
  (void);

#define Rte_Write_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct Rte_Write_ADLK_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct

Std_ReturnType
  Rte_Write_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct(UInt8 u);

#define Rte_Invalidate_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct Rte_Invalidate_ADLK_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct

Std_ReturnType
  Rte_Invalidate_VeOUT_ADLK_RLDoorMotorPWM_pct_VeOUT_ADLK_RLDoorMotorPWM_pct
  (void);

/* Entry point functions */
extern FUNC(void, ADLK_CODE) ADLK_Init(void);
extern FUNC(void, ADLK_CODE) ADLK_Step(void);

#endif
